[package]
name = "tpc9000/vapor"
version = "0.4.0-alpha.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["tpc9000"]

[dependencies]
TypeGuard = "tpc9000/typeguard@6.0.0-alpha.2"
TableUtil = "tpc9000/tableutil@0.8.1"
XSignal = "tpc9000/xsignal@3.0.1"
Cleaner = "tpc9000/cleaner@0.3.0"